# Generated by Django 5.0.4 on 2024-06-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('maCate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenCate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('maKH', models.AutoField(primary_key=True, serialize=False)),
                ('tenKH', models.TextField()),
                ('soDT', models.CharField(max_length=15)),
                ('eMail', models.EmailField(max_length=50)),
                ('diaChi', models.TextField()),
                ('gioiTinh', models.TextField()),
                ('tenDN', models.CharField(max_length=50)),
                ('matKhau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KichCo',
            fields=[
                ('maSize', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tenSize', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('maNCC', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenNCC', models.TextField()),
                ('diaChi', models.TextField()),
                ('soDT', models.CharField(max_length=15)),
                ('eMail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NhanHieu',
            fields=[
                ('maNH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenNH', models.TextField()),
                ('xuatXu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TinhTrangDonHang',
            fields=[
                ('maTT', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('tenTT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('maDM', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenDM', models.TextField()),
                ('maCate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('maHD', models.AutoField(primary_key=True, serialize=False)),
                ('ngayDatHang', models.DateField()),
                ('tongTien', models.IntegerField(default=0)),
                ('phuongThucThanhToan', models.CharField(default='Tiền mặt', max_length=50)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.khachhang')),
                ('tinhTrang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tinhtrangdonhang')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('maPN', models.AutoField(primary_key=True, serialize=False)),
                ('ngayNhap', models.DateField()),
                ('maNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('maSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenSP', models.TextField()),
                ('moTa', models.TextField()),
                ('giaBan', models.IntegerField()),
                ('chatLieu', models.TextField()),
                ('mauSac', models.TextField()),
                ('gioiTinh', models.CharField(choices=[('NAM', 'Nam'), ('NU', 'Nữ'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=6)),
                ('hinhanh', models.ImageField(null=True, upload_to='images/sanpham/')),
                ('hinhanh1', models.ImageField(null=True, upload_to='images/sanpham/')),
                ('kichCo', models.ManyToManyField(to='home.kichco')),
                ('maDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.danhmuc')),
                ('maNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nhacungcap')),
                ('maNH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nhanhieu')),
            ],
        ),
        migrations.CreateModel(
            name='QLSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongNhap', models.IntegerField(default=0)),
                ('soLuongXuat', models.IntegerField(default=0)),
                ('soLuongTonKho', models.IntegerField(default=0)),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.IntegerField()),
                ('donGia', models.IntegerField()),
                ('kichCo', models.CharField(max_length=10)),
                ('tongTien', models.IntegerField()),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.khachhang')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='CTPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongNhap', models.IntegerField(default=0)),
                ('donGiaNhap', models.IntegerField(default=0)),
                ('maPN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.phieunhap')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='CTHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kichCo', models.CharField(default='S', max_length=10)),
                ('soLuong', models.IntegerField(default=0)),
                ('donGiaBan', models.IntegerField(default=0)),
                ('thanhTien', models.IntegerField(default=0)),
                ('maHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hoadon')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ctpn',
            constraint=models.UniqueConstraint(fields=('maPN', 'maSP'), name='unique_maPN_maSP'),
        ),
        migrations.AddConstraint(
            model_name='cthd',
            constraint=models.UniqueConstraint(fields=('maHD', 'maSP'), name='unique_maHD_maSP'),
        ),
    ]
