# Generated by Django 5.0.4 on 2024-06-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.khachhang')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
            options={
                'unique_together': {('maKH', 'maSP')},
            },
        ),
    ]
