# Generated by Django 5.0.4 on 2024-06-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_yeuthich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemDanhGia', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('danhGia', models.TextField(blank=True, null=True)),
                ('ngayDanhGia', models.DateField(auto_now_add=True)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.khachhang')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
    ]
